### PR TITLE
MI-204 MapActivity UI refactored, improved code, error tolerance, robustness and improved usability for users

### PR DESCRIPTION
**Pull request by ghost**
Most of the commented out code in MapActivity should be gone. The non-interface methods have an XML documentation comment. Following C# coding conventions, the var initialization for variables was changed at some places where the type wasn't obvious on the right side of the expression.

A lot of code was moved around in MapActivity to make it easier for the developer and the interface should be less prone to errors. I added checks to make sure the GoogleApiClient is connected to prevent null LocationRequests. Methods were created to prevent code duplication when styling dialog boxes and when checking if the user is a driver/rider. Permissions are asked before opening the Map to prevent errors. As redesigned in the prototypes, instead of starting to use the application on the MapActivity, the main menu with big buttons is the first thing the users sees.

Also the main menu was added with updated buttons for better flow

### CODE REVIEW

**Comment by nim442** [comment]
Nice job on those icons. However, the descriptions are in the icon, they will only work in one language. We should add the text dynamically

**Comment by AlineTheAlien** [comment]
@nim442 you're right we didn't think about it, how should I incorporate them? just having the image with the dynamic text on top?

**Comment by AlineTheAlien** [comment]
@nim442 Please don't merge yet, I'm changing the main menu buttons! The buttons will now only have icons, the texts will be below the icons in their respective textviews, therefore they will be able to get translated 👍

**Comment by nim442** [comment]
👍

**Comment by nim442** [comment]
Nice job Merging

**Pull request merged**
